GET http://localhost:3000

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "id": "asset3",
    "symbol": "A2"
}

###
GET http://localhost:3000/assets

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "asset_id": "aaaa",
    "price": 1
}

###
GET http://localhost:3000/orders